### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by dabuchera** [holepunchto/filesharing-react-app-example#1]
Running into similar problems as desribed in the keet chat.

OS: Windows

![image](https://github.com/holepunchto/filesharing-react-app-example/assets/53481997/84137137-8a0a-4fdf-a4c2-cf2f1e8144c6)

**Comment by dabuchera** [comment]
Comment on the above:
It is a Windows bug. Was trying in Ubuntu 22.04.3 LTS and everything worked fine. 
Just had to disable gpu accelaration for chromium when chrome running in parallel:

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[13227:0219/105058.779092:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[13227:0219/105059.791180:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
2024-02-19T09:50:59.979Z electron-main exiting due to uncaught exception
key=pqbzjhqyonxprx8hghxexnmctw75mr91ewqw5dxe1zmntfyaddqy
length=2494
fork=0
platform=linux
arch=x64
pid=12830
uptime=4.916832725s
stack=SyntaxError: Bad control character in string literal in JSON at position 876976
    at JSON.parse (<anonymous>)
    at Object.decode (eval at module.exports (/local/home/dbucher/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:418:17)
    at Object.decode (eval at module.exports (/local/home/dbucher/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:21:32)
    at Object.recv (eval at module.exports (/local/home/dbucher/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:201:45)
    at Channel._recv (eval at module.exports (/local/home/dbucher/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:157:27)
    at Protomux._decode (eval at module.exports (/local/home/dbucher/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:460:15)
    at Protomux._ondata (eval at module.exports (/local/home/dbucher/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:424:12)
    at FramedStream.emit (node:events:513:28)
    at ReadableState.drain (eval at module.exports (/local/home/dbucher/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:336:64)
    at ReadableState.update (eval at module.exports (/local/home/dbucher/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:346:12)
```


Maybe there is a possibility to add similar lines as below to the electron setup of pear

```
const { app } = require('electron');
 app.disableHardwareAcceleration();
 app.on('ready', () => {
   // Your app initialization code here
 });
```

**Comment by dabuchera** [comment]
Know issue:

https://github.com/electron/electron/issues/40727

**Comment by mafintosh** [comment]
cc @davidmarkclements lets add an option for that in pkg.json.pear

**Comment by serapath** [comment]
same issue here.

`pear dev` or `pear dev -t` starts
once i start a second instance it crashes both.

(latest linux mint on lenovo thinkpad)

```
$ pear dev -t
2024-02-22T00:42:24.657Z electron-main exiting due to uncaught exception
key=pqbzjhqyonxprx8hghxexnmctw75mr91ewqw5dxe1zmntfyaddqy
length=2494
fork=0
platform=linux
arch=x64
pid=111067
uptime=12.302366024s
stack=SyntaxError: Bad control character in string literal in JSON at position 4662324
    at JSON.parse (<anonymous>)
    at Object.decode (eval at module.exports (/home/serapath/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:418:17)
    at Object.decode (eval at module.exports (/home/serapath/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:21:32)
    at Object.recv (eval at module.exports (/home/serapath/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:201:45)
    at Channel._recv (eval at module.exports (/home/serapath/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:157:27)
    at Protomux._decode (eval at module.exports (/home/serapath/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:460:15)
    at Protomux._ondata (eval at module.exports (/home/serapath/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:424:12)
    at FramedStream.emit (node:events:513:28)
    at ReadableState.drain (eval at module.exports (/home/serapath/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:336:64)
    at ReadableState.update (eval at module.exports (/home/serapath/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/1/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:346:12)
```

**Comment by serapath** [comment]
@davidmarkclements is there an easy fix? i would love to rebuild this app without react, but am kinda stuck with this error atm, but maybe i can help to fix it.
