### ISSUE TITLE
issue in run

### ISSUE THREAD

**Issue by Acktarius** [holepunchto/filesharing-react-app-example#3]
works with `pear dev`, then *staged* and *seed*, but `pear run pear://xfg7...` return an error :  
> /node_modules/compact-encoding/index.js+app+app:348
      state.buffer.set(s, state.start)
                   ^
RangeError: offset is out of bounds
    at Buffer.set (<anonymous>)
    at Object.encode (/node_modules/compact-encoding/index.js+app+app:348:20)
    at Request._encodeRequest (/node_modules/dht-rpc/lib/io.js+app+app:424:32)
    at Request.send (/node_modules/dht-rpc/lib/io.js+app+app:328:52)
    at HyperDHT._request (/node_modules/dht-rpc/index.js+app+app:290:9)
    at Query._visit (/node_modules/dht-rpc/lib/query.js+app+app:328:26)
    at Query._readMore (/node_modules/dht-rpc/lib/query.js+app+app:162:12)
    at Query._read (/node_modules/dht-rpc/lib/query.js+app+app:150:10)
    at ReadableState.update (/node_modules/streamx/index.js+app+app:348:16)
    at ReadableState.updateReadNT (/node_modules/streamx/index.js+app+app:525:10)

> Node.js v18.15.0
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:93919)
    at _.sendToFrame (node:electron/js2c/browser_init:2:79757)
    at e.reply (node:electron/js2c/browser_init:2:87031)
    at eval (eval at module.exports (/home/ccxbeelink/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/2/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:381:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IpcMainImpl.eval (eval at module.exports (/home/ccxbeelink/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/2/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:325:16)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:93919)
    at _.sendToFrame (node:electron/js2c/browser_init:2:79757)
    at e.reply (node:electron/js2c/browser_init:2:87031)
    at eval (eval at module.exports (/home/ccxbeelink/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/2/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:381:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IpcMainImpl.eval (eval at module.exports (/home/ccxbeelink/.config/pear/by-dkey/7216eeac5c879a2ca1dcff14bb8c1ad47d188a8c17b13e66f36d354ea8bd3b28/2/by-arch/linux-x64/bin/pear-runtime-app/resources/app/node_modules/node-bare-bundle/compile.js:3:4), <anonymous>:325:16)
[29125:0402/143032.177055:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[29125:0402/143046.330306:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[29125:0402/143046.331693:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

--- 

any idea ?

**Comment by freeall** [comment]
@Acktarius I just did `pear stage foo`, `pear seed foo`, and then ran it. I can confirm that I run into the same issue.

If I do that with a clean app from `pear init` then it works. So clearly something's going on with this one.

I'll investigate a bit.

**Comment by freeall** [comment]
There was an issue with trying to join the swarm at `app.key` which was loaded with `Buffer.from`. It's always best to use `hypercore-id-encoding`.

Fixed in https://github.com/holepunchto/filesharing-react-app-example/commit/89ce31a810b331ec22ff898267f5a55104beb082.

@Acktarius can you see if this works for you as well?

**Comment by Acktarius** [comment]
Thanks for looking into it, I made good progress, and now can pass the **run** step.  
here is what I made :  
`git clone https://github.com/holepunchto/filesharing-react-app-example.git ./filesharing-react-app-example-Template`

`mkdir filesharing-react-app-example`  
`cd filesharing-react-app-example`  
`pear init -y`  
`rm -rf *`  
`mv ../filesharing-react-app-example-Template/* ./`
`npm install`
`rm package.json.lock`  
`npm install @emotion/styled @mui/icons-material @mui/material corestore downloads-folder htm hyperbee hypercore-id-encoding hyperdrive hyperswarm localdrive protomux-rpc react react-dom styled-components pear-inspect`  
`npm i --package-lock-only`  
`pear dev`   
`pear stage <name> --dry-run`  
`pear stage <name>`  
`pear release <name>`  
`pear seed <name>`  

*( installed all the packages, because* `npm install` *seemed to do a good job, but* `pear dev` *didn't work, that why I reinstall all of them an re run package-lock-only)*

`pear run pear://4qkp...` 
* it works ! I was able to change user name and load a file
* still a *stale* error, due to **electron** version I think:  
> [50834:0403/145559.996934:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

tried in an other terminal `pear run pear://4qkp...`  `<name>`  
and it works, thanks a lot !!!

**Comment by Acktarius** [comment]
I spoke a bit too fast, it works and I can connect from on computer to the other and see the share files, but when I click to download a peer file, I get the following Error :  
Could not start download of *filename*. Maybe the network does not have the file.

**Comment by freeall** [comment]
I don't get that error. Can you try to reproduce again? I added an alert message when file is downloaded, to give a bit better response.

Also added a readme that can help with which `pear` commands to run.

**Comment by Acktarius** [comment]
I 'n no longer able to reproduce the error. It was creating the file in the Download folder , size 0 bytes.
in the mean time, I had everything reboot, seems it solved it.  

Thanks for the readme, that will definitely help others.
